from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum, auto
from typing import List, Optional, Dict, Any


class HarmTier(Enum):
    T1_MINIMAL = auto()
    T2_CONCERNING = auto()
    T3_HIGH = auto()
    T4_CASCADING = auto()
    T5_EXTINCTION = auto()


class Domain(Enum):
    HUMAN = "H-SIG"
    ARTIFICIAL = "A-SIG"
    ECOLOGICAL = "E-SIG"


@dataclass
class HarmSignal:
    """Represents a raw harm signal coming into the engine."""
    id: str
    domains: List[Domain]
    description: str
    evidence_refs: List[str]  # URIs, hashes, IDs, etc.
    reported_at: datetime
    involves_minors: bool = False
    involves_species_risk: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ValidatedHarm:
    """Result of interpretation pipeline classification and validation."""
    signal: HarmSignal
    tier: HarmTier
    validated_domains: List[Domain]
    validation_notes: str
    validation_time: datetime


@dataclass
class InterventionWindow:
    """Represents a time-limited intervention authority window."""
    id: str
    harm: ValidatedHarm
    opened_at: datetime
    expires_at: datetime
    max_expires_at: datetime
    renewed_count: int = 0
    active: bool = True

    def is_expired(self, now: Optional[datetime] = None) -> bool:
        now = now or datetime.utcnow()
        return not self.active or now >= self.expires_at or now >= self.max_expires_at


@dataclass
class Decision:
    """Represents a decision generated by the decision engine."""
    id: str
    harm: ValidatedHarm
    recommended_actions: List[str]
    created_at: datetime
    dissolution_condition: str  # description of when authority must dissolve
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TribunalRuling:
    """Represents a tribunal ruling, separate from the engine itself."""
    id: str
    decision: Decision
    text: str
    issued_at: datetime
    tier: HarmTier
    intervention_window_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)